version: '3.8'

services:
  tverrec:
    container_name: bulkdownload
    image: dongaba/tverrec:latest
    hostname: 'tverrec'
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"

    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      POWERSHELL_TELEMETRY_OPTOUT: 1
      COMPOSE_PROJECT_NAME: tverrec

    tmpfs:
      - /mnt/Temp

    volumes:
      - type: bind
        source: ~/ContainerData/Work
        target: /mnt/Work
      - type: bind
        source: ~/ContainerData/Video
        target: /mnt/Video
      - type: bind
        source: ~/ContainerData/container-data
        target: /app/TVerRec/container-data

    cap_add:
      - ALL

    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
