name: Push to Docker Hub

on:
  push:
    branches: [master]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: dongaba/tverrec

jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      #Set Tag Name
      - name: Set Tag Name as Preparation
        id: prep
        run: |
          TAG="latest"
          echo "tag=${IMAGE_NAME}:${TAG}" >> $GITHUB_OUTPUT

      #Check out
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: master

      #Collect metadata
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          #images: dongaba/tverrec
          images: ${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      #Build Preperation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      #Confirm available platforms
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      #Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      #Build & Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./resources/docker
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: mode=max
          tags: ${{ steps.prep.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

      #Push README.md to Docker Hub
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./README.md
